name: appflores_mobile
description: A hybrid mobile application for intelligent digital specimen repositories.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.3
  
  # HTTP Client for API
  dio: ^5.3.3
  
  # 3D Engine / Viewer
  flutter_gl: ^0.0.14
  model_viewer_plus: ^1.7.0
  
  # Routing
  go_router: ^11.1.2
  
  # NFC Reading
  nfc_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
